package models

import "time"

type Resource struct {
	Uid                    string      `json:"uid,omitempty"`
	ResourceId             string      `json:"Resource.resourceId,omitempty"`
	RemoteId               string      `json:"Resource.remoteId,omitempty"`
	Accesscode             string      `json:"-,omitempty"`
	Index                  int         `json:"Resource.index,omitempty"`
	Proof                  int         `json:"Resource.proof,omitempty"`
	Data                   []Resource  `json:"Resource.data,omitempty"`
	ItsHash                string      `json:"Resource.itsHash,omitempty"`
	PrevHash               string      `json:"Resource.prevHash,omitempty"`
	Timestamp              string      `json:"Resource.timestamp,omitempty"`
	Category               *Resource   `json:"Resource.category,omitempty"`
	Categories             []Resource  `json:"Resource.categories,omitempty"`
	ChildOf                *Resource   `json:"Resource.childOf,omitempty"`
	Metadata               []Resource  `json:"Resource.metadata,omitempty"`
	Name                   string      `json:"Resource.name,omitempty"`
	Identifier             string      `json:"Resource.identifier,omitempty"`
	Label                  string      `json:"Resource.label,omitempty"`
	Description            string      `json:"Resource.description,omitempty"`
	Icon                   int         `json:"Resource.icon,omitempty"`
	MetaKey0               string      `json:"Resource.metaKey0,omitempty"`
	MetaKey1               string      `json:"Resource.metaKey1,omitempty"`
	MetaKey2               string      `json:"Resource.metaKey2,omitempty"`
	MetaKey3               string      `json:"Resource.metaKey3,omitempty"`
	MetaKey4               string      `json:"Resource.metaKey4,omitempty"`
	MetaKey5               string      `json:"Resource.metaKey5,omitempty"`
	MetaKey6               string      `json:"Resource.metaKey6,omitempty"`
	MetaKey7               string      `json:"Resource.metaKey7,omitempty"`
	MetaKey8               string      `json:"Resource.metaKey8,omitempty"`
	MetaKey9               string      `json:"Resource.metaKey9,omitempty"`
	MetaKey10              string      `json:"Resource.metaKey10,omitempty"`
	MetaBoolean0           bool        `json:"Resource.metaBoolean0,omitempty"`
	MetaBoolean1           bool        `json:"Resource.metaBoolean1,omitempty"`
	MetaBoolean2           bool        `json:"Resource.metaBoolean2,omitempty"`
	MetaBoolean3           bool        `json:"Resource.metaBoolean3,omitempty"`
	MetaBoolean4           bool        `json:"Resource.metaBoolean4,omitempty"`
	MetaBoolean5           bool        `json:"Resource.metaBoolean5,omitempty"`
	MetaBoolean6           bool        `json:"Resource.metaBoolean6,omitempty"`
	MetaBoolean7           bool        `json:"Resource.metaBoolean7,omitempty"`
	MetaBoolean8           bool        `json:"Resource.metaBoolean8,omitempty"`
	MetaBoolean9           bool        `json:"Resource.metaBoolean9,omitempty"`
	MetaBoolean10          bool        `json:"Resource.metaBoolean10,omitempty"`
	MetaIntValue0          int         `json:"Resource.metaIntValue0,omitempty"`
	MetaIntValue1          int         `json:"Resource.metaIntValue1,omitempty"`
	MetaIntValue2          int         `json:"Resource.metaIntValue2,omitempty"`
	MetaIntValue3          int         `json:"Resource.metaIntValue3,omitempty"`
	MetaIntValue4          int         `json:"Resource.metaIntValue4,omitempty"`
	MetaIntValue5          int         `json:"Resource.metaIntValue5,omitempty"`
	MetaIntValue6          int         `json:"Resource.metaIntValue6,omitempty"`
	MetaIntValue7          int         `json:"Resource.metaIntValue7,omitempty"`
	MetaIntValue8          int         `json:"Resource.metaIntValue8,omitempty"`
	MetaIntValue9          int         `json:"Resource.metaIntValue9,omitempty"`
	MetaIntValue10         int         `json:"Resource.metaIntValue10,omitempty"`
	MetaMultiIntValue      []int       `json:"Resource.metaMultiIntValue,omitempty"`
	MetaStringValue0       string      `json:"Resource.metaStringValue0,omitempty"`
	MetaStringValue1       string      `json:"Resource.metaStringValue1,omitempty"`
	MetaStringValue2       string      `json:"Resource.metaStringValue2,omitempty"`
	MetaStringValue3       string      `json:"Resource.metaStringValue3,omitempty"`
	MetaStringValue4       string      `json:"Resource.metaStringValue4,omitempty"`
	MetaStringValue5       string      `json:"Resource.metaStringValue5,omitempty"`
	MetaStringValue6       string      `json:"Resource.metaStringValue6,omitempty"`
	MetaStringValue7       string      `json:"Resource.metaStringValue7,omitempty"`
	MetaStringValue8       string      `json:"Resource.metaStringValue8,omitempty"`
	MetaStringValue9       string      `json:"Resource.metaStringValue9,omitempty"`
	MetaStringValue10      string      `json:"Resource.metaStringValue10,omitempty"`
	MetaMultiStringValue   []string    `json:"Resource.metaMultiStringValue,omitempty"`
	MetaFloatValue0        float64     `json:"Resource.metaFloatValue0,omitempty"`
	MetaFloatValue1        float64     `json:"Resource.metaFloatValue1,omitempty"`
	MetaFloatValue2        float64     `json:"Resource.metaFloatValue2,omitempty"`
	MetaFloatValue3        float64     `json:"Resource.metaFloatValue3,omitempty"`
	MetaFloatValue4        float64     `json:"Resource.metaFloatValue4,omitempty"`
	MetaFloatValue5        float64     `json:"Resource.metaFloatValue5,omitempty"`
	MetaFloatValue6        float64     `json:"Resource.metaFloatValue6,omitempty"`
	MetaFloatValue7        float64     `json:"Resource.metaFloatValue7,omitempty"`
	MetaFloatValue8        float64     `json:"Resource.metaFloatValue8,omitempty"`
	MetaFloatValue9        float64     `json:"Resource.metaFloatValue9,omitempty"`
	MetaFloatValue10       float64     `json:"Resource.metaFloatValue10,omitempty"`
	MetaMultiFloatValue    []float64   `json:"Resource.metaMultiFloatValue,omitempty"`
	MetaResourceValue      *Resource   `json:"Resource.metaResourceValue,omitempty"`
	MetaMultiResourceValue []Resource  `json:"Resource.metaMultiResourceValue,omitempty"`
	MetaDateValue0         time.Time   `json:"Resource.metaDateValue0,omitempty"`
	MetaDateValue1         time.Time   `json:"Resource.metaDateValue1,omitempty"`
	MetaDateValue2         time.Time   `json:"Resource.metaDateValue2,omitempty"`
	MetaDateValue3         time.Time   `json:"Resource.metaDateValue3,omitempty"`
	MetaDateValue4         time.Time   `json:"Resource.metaDateValue4,omitempty"`
	MetaDateValue5         time.Time   `json:"Resource.metaDateValue5,omitempty"`
	MetaDateValue6         time.Time   `json:"Resource.metaDateValue6,omitempty"`
	MetaDateValue7         time.Time   `json:"Resource.metaDateValue7,omitempty"`
	MetaDateValue8         time.Time   `json:"Resource.metaDateValue8,omitempty"`
	MetaDateValue9         time.Time   `json:"Resource.metaDateValue9,omitempty"`
	MetaDateValue10        time.Time   `json:"Resource.metaDateValue10,omitempty"`
	MetaMultiDateValue     []time.Time `json:"Resource.metaMultiDateValue,omitempty"`
	Coordinates            []float64   `json:"Resource.coordinates,omitempty"`
	Owner                  *Resource   `json:"Resource.owner,omitempty"`
	Resources              []Resource  `json:"Resource.resources,omitempty"`
	Creator                *Resource   `json:"Resource.creator,omitempty"`
	Activities             []Resource  `json:"Resource.activities,omitempty"`
	Party                  *Resource   `json:"Resource.party,omitempty"`
	Transactions           []Resource  `json:"Resource.transactions,omitempty"`
	Resource               *Resource   `json:"Resource.resource,omitempty"`
	Assignments            []Resource  `json:"Resource.assignments,omitempty"`
	Version                *Resource   `json:"Resource.version,omitempty"`
	Versions               []Resource  `json:"Resource.versions,omitempty"`
	Date                   time.Time   `json:"Resource.date,omitempty"`
	CreatedAt              time.Time   `json:"Resource.createdAt,omitempty"`
	IsTrashed              bool        `json:"Resource.isTrashed,omitempty"`
	DType                  []string    `json:"dgraph.type,omitempty"`
}
