openapi: 3.0.0
info:
  title: Savannah Order Management API
  version: 1.0.0
  description: API for managing orders and customers in the Savannah system.
servers:
  - url: http://localhost:3000
paths:
  /customers:
    post:
      summary: Add a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the customer
                code:
                  type: string
                  description: The unique code of the customer
                phone:
                  type: string
                  description: The phone number of the customer
            example:
              name: John Doe
              code: ABC123
              phone: +1234567890
      responses:
        '201':
          description: Customer added successfully
        '400':
          description: Bad request. Invalid request body.
        '500':
          description: Internal server error. Failed to add customer to the database.

  /orders:
    post:
      summary: Add a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                  description: The ID of the customer placing the order
                item:
                  type: string
                  description: The item being ordered
                amount:
                  type: number
                  format: float
                  description: The amount of the order
                time:
                  type: string
                  format: date-time
                  description: The time the order was placed
            example:
              customer_id: 1
              item: Pizza
              amount: 200.00
              time: "2024-02-21T12:00:00Z"
      responses:
        '201':
          description: Order added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Confirmation message
                  order_id:
                    type: integer
                    description: The ID of the newly created order
        '400':
          description: Bad request. Invalid request body.
        '500':
          description: Internal server error. Failed to add order to the database.

